name: ROS2 CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - uses: actions/checkout@v4
        with:
          repository: https://github.com/1r0b1n0/libros2qt
          path: ros_ws/src
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: ros2_qtcanbus ros2_qtcanbus_msg
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""