name: ROS2 CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - rolling
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src/deps/libros2qt ros_ws/src/ros2_qtcanbus
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src/ros2_qtcanbus
      - uses: actions/checkout@v4
        with:
          repository: 1r0b1n0/libros2qt
          path: ros_ws/src/deps/libros2qt
      #- name: Install Qt
      #  uses: jurplel/install-qt-action@v3          
      - name: install deps
        run: sudo apt-get -y install qtbase5-dev libqt5serialbus5-dev python3-numpy
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: ros2_qtcanbus ros2_qtcanbus_msg
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""